### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by Red-exe-Engineer** [ultimate-research/nnsdk-rs#42]
Yeah I'm new to Rust... could you perchance give a simple example?
Or perhaps if I figure out how to use it I could make a pull request?

**Comment by wangziming133** [comment]
I also want to know how to use it. It just seems that Rust doesn't support Nintendo Switch.

**Comment by Raytwo** [comment]
Use this: https://github.com/jam1garner/cargo-skyline
